# .streamlit/config.toml

[server]
# Run in headless mode (this is the default on Streamlit Cloud)
headless = true
# Specify a port (optional)
port = 8501


[browser]
# Prevent Streamlit from gathering usage stats
gatherUsageStats = false
