# .streamlit/config.toml

[server]
# Run in headless mode (this is the default on Streamlit Cloud)
headless = true
# Specify a port (optional)
port = 8501
# Disable CORS if needed (be cautious with this in production)
enableCORS = false

[browser]
# Prevent Streamlit from gathering usage stats
gatherUsageStats = false
